site_name: "StarCraft: Archiwum Zasad"
site_description: "Nieoficjalne polskie tłumaczenie StarCraft: The Miniatures Game"
theme:
  name: material
  language: pl
  palette:
    - scheme: slate  # Ciemny motyw pasujący do klimatu Sci-Fi
      primary: dark blue
      accent: blue
  features:
    - navigation.tabs # Górne zakładki dla Twoich Kategorii
    - navigation.sections
    - navigation.expand
    - content.tabs.link
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

nav:
  - 'Główna': index.md
  - 'Kategoria Pierwsza: Zasady':
      - 'Wstęp i Podstawy': zasady/index.md
      - 'Rozdział 2: Podstawowe Pojęcia': zasady/rozdzial-2.md
      - 'Rozdział 3: Kości i Rzuty': zasady/rozdzial-3.md
      - 'Rozdział 4: Pomiar i Ruch': zasady/rozdzial-4.md
      - 'Rozdział 5: Karty i Cechy': zasady/rozdzial-5.md
      - 'Rozdział 6: System Zaopatrzenia': zasady/rozdzial-6.md
      - 'Rozdział 7: Pole Bitwy': zasady/rozdzial-7.md
      - 'Rozdział 8: Sekwencja Gry': zasady/rozdzial-8.md
      - 'Rozdział 9: Przygotowanie do Bitwy': zasady/rozdzial-9.md
      - 'Rozdział 10: Zasady Zaawansowane': zasady/rozdzial-10.md
      - 'Rozdział 11: Słownik Słów Kluczowych i Definicji': zasady/rozdzial-11.md
      - 'Rozdział 12: Przegląd Zasad': zasady/rozdzial-12.md
  - 'Kategoria Druga: Frakcje i Karty':
      - 'Przegląd Frakcji': frakcje/index.md
      - 'Protoss': frakcje/protoss.md
      - 'Terran': frakcje/terran.md
      - 'Zerg': frakcje/zerg.md
  - 'Kategoria Trzecia: Karty Misji':
      - 'Draft i Rozstawienie': misje/index.md

markdown_extensions:
  - tables
  - admonition          # To aktywuje bloki !!!
  - pymdownx.details # Odpowiada za rozwijane bloki (spoiler/accordion)
  - pymdownx.superfences
  - attr_list
